### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by wyk111wyk** [EnesKaraosman/SwipeCell#1]
![截屏2020-09-24 下午2 37 26](https://user-images.githubusercontent.com/8171481/94109583-c94a3800-fe73-11ea-89ef-9ab8d3323a70.png)

**Comment by EnesKaraosman** [comment]
Thanks for reporting.

Sorry, happened a git issue I guess, fixed in the version `0.1.1` can you try again please @wyk111wyk
