### ISSUE TITLE
Tap to collapse gesture interferes with navlink tap gesture

### ISSUE THREAD

**Issue by jjkaufman** [EnesKaraosman/SwipeCell#3]
Thanks for creating this library! I am using it with NavLinks and am having the problem of the tap gesture (used to dismiss the actions) causing navlink taps to stop working.

I've found a solution by having the tap to close gesture be included on a conditional rectangle. Will open a PR

**Comment by EnesKaraosman** [comment]
Thanks for contributing, accepted PR #4
