### ISSUE TITLE
Cannot find 'Slot' in scope

### ISSUE THREAD

**Issue by Djibs** [EnesKaraosman/SwipeCell#5]
Hello,

Thanks for your code.

After installing the project in xcode (12.5), I copied your example but got an error. Xcode cannot find "Slot" 

![DJIBS 2021-06-16 à 09 08 04](https://user-images.githubusercontent.com/1236842/122173732-5dd14c00-ce82-11eb-83f1-d7580feea9ed.jpg)

**Comment by EnesKaraosman** [comment]
Did you import the package with saying;
`import SwipeCell` ?
